### ISSUE TITLE
 *** No rule to make target 'packet-j2735.c', needed by 'register.c'.

### ISSUE THREAD

**Issue by AhmedElshaarany** [wayties/wireshark#2]
Hi,

I switched to the v2x branch and ran the following commands:
`autoreconf --install &&
./configure &&
make`

But `make` gave the error below:

make[4]: Entering directory '/wireshark/epan/dissectors'
  PYTHON   packet-ncp2222.c
Processing NCP definitions...
Defined 563 NCP types.
make[4]: *** No rule to make target 'packet-j2735.c', needed by 'register.c'.  Stop.
make[4]: Leaving directory '/wireshark/epan/dissectors'
Makefile:2085: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/wireshark/epan'
Makefile:1191: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/wireshark/epan'
Makefile:3411: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/wireshark'
Makefile:1740: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by stevekwon** [comment]
cd epan/dissectors/asn1 **<- go to ASN.1 directory**
make **<- it will generate "packet-j2735.c"**
cd -   **<- back to top directory**
make **<- build again**

Before generating packet-j2735.c, don't forget to modify MIN_DSRC_MSG, DSRC_MSG_NAME and DSRC_MSG_ABBR in "packet-j2735-template.c"

**Comment by AhmedElshaarany** [comment]
Hi Steve,

Thank you for your reply.

Can you please elaborate on what these parameters are and maybe provide an example on how to modify them?

Thanks!

**Comment by stevekwon** [comment]
MIN_DSRC_MSG is the first DSRC UPER message id number.
DSRC_MSG_NAME is a message name and DSRC_MSG_ABBR is abbreviation to show on Wireshark UI.
You can find them in SAE J2735 standard document.

**Comment by AhmedElshaarany** [comment]
Thank you for your reply, Steve! I was able to modify the "packet-j2735-template.c" file according to the SAE J2735 standard document.
However, after running the c.sh script on the original ASN.1 file to create the fixed one and following the steps you mentioned to create generate the packet-j2735.c file, I ran into the error below:

make[1]: Entering directory '/V2X_Wireshark/wireshark/epan/dissectors/asn1/j2735'
/usr/bin/python ../../../../tools/asn2wrs.py \
	-E -L \
	-p j2735 \
	-c ./j2735.cnf \
	-D . \
	 J2735_201603DA_fix.asn 
ASN.1 to Wireshark dissector compiler
Traceback (most recent call last):
  File "../../../../tools/asn2wrs.py", line 8039, in <module>
    eth_main()
  File "../../../../tools/asn2wrs.py", line 7971, in eth_main
    ast.extend(yacc.parse(data, lexer=lexer, debug=pd))
  File "/V2X_Wireshark/wireshark/tools/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/V2X_Wireshark/wireshark/tools/yacc.py", line 1049, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/V2X_Wireshark/wireshark/tools/lex.py", line 386, in token
    newtok = self.lexerrorf(tok)
  File "../../../../tools/asn2wrs.py", line 418, in t_error
    raise LexError(t, input_file)
__main__.LexError: J2735_201603DA_fix.asn:1: Unexpected character '\xef'
Makefile:700: recipe for target 'j2735-exp.cnf' failed
make[1]: *** [j2735-exp.cnf] Error 1
make[1]: Leaving directory '/V2X_Wireshark/wireshark/epan/dissectors/asn1/j2735'
Makefile:690: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by stevekwon** [comment]
It is a kind of UTF-8 encoding problem.
Remove the Unicode BOM and convert to ASCII as followings. After that, try again.

sudo apt-get install icu-devtools (if you don't have "uconv")
uconv --remove-signature -t ASCII J2735_201603DA.ASN > J2735_201603DA.asn

**Comment by AhmedElshaarany** [comment]
Thank you for your time and help, I really appreciate it!

**Comment by merekemess** [comment]
I read the SAE J2735 document. It does not explain this fix. The uper frame id is in there spec but what do i edit in the /epan/dissectors/asn1/j2735/packet-j2735-template.c ?

Is this a secret or something?

**Comment by stevekwon** [comment]
There is no secret, it is just not included because of copyright problem.
As I mention in my slide, it is the exactly same procedure as my "wsm" or "wsa" dissectors which are  fully implemented.
First of all, you understand how to map ASN1 tag using identifier class. Then fix j2735.cnf and packet-j2735-template.c like "wsm" or "wsa" by J2945.

**Comment by merekemess** [comment]
Thank you.
